<?php
declare(strict_types=1);

require_once '../Include/Config.php';

// This file is generated by Composer
require_once dirname(__FILE__) . '/../vendor/autoload.php';

use Slim\Factory\AppFactory;
use Slim\HttpCache\Cache;
use DI\Container;

use EcclesiaCRM\Slim\Middleware\VersionMiddleware;

$rootPath = str_replace('/ident/index.php', '', $_SERVER['SCRIPT_NAME']);

// Instantiate the app
$container = new Container();

$settings = require __DIR__.'/../Include/slim/settings.php';
$settings($container);

AppFactory::setContainer($container);

$app = AppFactory::create();

// Register the http cache middleware.
//$app->add( new Cache('private', 0) );

$app->setBasePath($rootPath . "/ident");

// Set up
require_once __DIR__.'/dependencies.php';
require_once __DIR__ . '/../Include/slim/error-handler.php';

// routes
require_once __DIR__ . '/routes/verify.php';


// Run app
$app->run();
