<?php
declare(strict_types=1);

require_once '../Include/Config.php';

// This file is generated by Composer
require_once dirname(__FILE__) . '/../vendor/autoload.php';

use Slim\Factory\AppFactory;
use DI\Container;

use EcclesiaCRM\PluginQuery;

$rootPath = str_replace('/ident/index.php', '', $_SERVER['SCRIPT_NAME']);

// Instantiate the app
$container = new Container();

AppFactory::setContainer($container);

$app = AppFactory::create();

// Register the http cache middleware.
//$app->add( new Cache('private', 0) );

$app->setBasePath($rootPath . "/ident");

// Set up
require_once __DIR__.'/dependencies.php';
require_once __DIR__ . '/../Include/slim/error-handler.php';

// routes
require_once __DIR__ . '/routes/verify.php';

$plugins = PluginQuery::create()
    ->findByActiv(true);

foreach ($plugins as $plugin) {
    $routes = scandir(__DIR__.'/../Plugins/'.$plugin->getName().'/ident/routes/');

    foreach ($routes as $route) {
        if (!in_array($route, [".", ".."]) and $route != "") {
            $path = __DIR__ . '/../Plugins/' . $plugin->getName() . '/ident/routes/' . $route;

            if (file_exists($path)) {
                require_once $path;
            }
        }
    }
}


// Run app
$app->run();
