<?php

//
//  This code is under copyright not under MIT Licence
//  copyright   : 2025 Philippe Logel all right reserved not MIT licence
//                This code can't be included in another software
//
//  Updated : 2025/07/28
//


/*
Via the crontab
usage : php "path_to_dir"/backuptools/backup.php iRemote=0 iArchiveType="3" bEncryptBackup=false password=""
don't forget : chown -R www-data:www-data "path_to_dir"/tmp_attach
 */

declare(strict_types=1);

require_once '../Include/Config.php';

// This file is generated by Composer
require_once dirname(__FILE__).'/../vendor/autoload.php';

use EcclesiaCRM\Backup\CreateBackup;
use EcclesiaCRM\Utils\LoggerUtils;

if (!empty($argv[1])) {
	print(var_dump($argc));

	$input = new stdClass();
	
	for ($i=1;$i<$argc;$i++) {
		$arguments = explode ("=", $argv[$i]);

		switch ($i) {
			case 1:
				$input->{$arguments[0]} = intval($arguments[1]);
				break;
			case 3:
				$input->{$arguments[0]} = ($arguments[1]=="false")?false:true;
				break;
			default:
				$input->{$arguments[0]} = $arguments[1];
		}
		
	}

	//var_dump($input);

	if (file_exists('../tmp_attach/backup_result.json')) {
		unlink('../tmp_attach/backup_result.json');
	}

	$fp = fopen('../tmp_attach/backup_in_progress.txt', 'w');
	fwrite($fp, date('l jS \of F Y h:i:s A'));
	fclose($fp);
	

	$logger = LoggerUtils::getAppLogger();

	$createBackup = new CreateBackup($input);
	$backup = $createBackup->run();

	$res = get_object_vars($backup);

	if (file_exists('../tmp_attach/backup_in_progress.txt')) {
		unlink('../tmp_attach/backup_in_progress.txt');
	}

	file_put_contents('../tmp_attach/backup_result.json', json_encode($res));
}
