<?php
declare(strict_types=1);

require_once '../Include/Config.php';

// This file is generated by Composer
require_once dirname(__FILE__).'/../vendor/autoload.php';

use Slim\Factory\AppFactory;
use Slim\Middleware\ContentLengthMiddleware;
use DI\Container;

use EcclesiaCRM\Slim\Middleware\VersionMiddleware;
use Tuupola\Middleware\JwtAuthentication;

use EcclesiaCRM\SessionUser;
use EcclesiaCRM\PluginQuery;

use Propel\Runtime\ActiveQuery\Criteria;

use EcclesiaCRM\Utils\RedirectUtils;
use EcclesiaCRM\dto\SystemURLs;

use EcclesiaCRM\Slim\Error\handlers;

// security access, if no user exit
if (SessionUser::getId() ==  0) RedirectUtils::Redirect('session/login');

$rootPath = str_replace('/api/index.php', '', $_SERVER['SCRIPT_NAME']);

// Instantiate the app
$container = new Container();

AppFactory::setContainer($container);

$app = AppFactory::create();

$contentLengthMiddleware = new ContentLengthMiddleware();
$app->add($contentLengthMiddleware);

// Register the http cache middleware : unusefull
//$app->add( new Cache('private', 0) );

$app->setBasePath($rootPath . "/api");

$app->add( new VersionMiddleware() );

$app->add(new JwtAuthentication([
    "secret" => SessionUser::getUser()->getJwtSecretForApi(),
    //"cookie" => SessionUser::getUser()->getUserNameForApi(),
    "ignore" => [SystemURLs::getRootPath()."/api/families", SystemURLs::getRootPath(). "/api/persons/", SystemURLs::getRootPath()."/api/system/csp-report", 
        SystemURLs::getRootPath()."/api/systemupgrade/isUpdateRequired", 
        SystemURLs::getRootPath()."/api/filemanager/getFile/", SystemURLs::getRootPath()."/api/synchronize/page",
        SystemURLs::getRootPath(). "/api/database",
        SystemURLs::getRootPath(). "/api/plugins",
        SystemURLs::getRootPath(). "/api/groups/addressbook/extract/",
        SystemURLs::getRootPath(). "/api/cart/addressbook/extract"
    ],
    "algorithm" => "HS256",
    "error" => function ($response, $arguments) {
        $data["status"] = "error";
        $data["message"] = $arguments["message"];
        return $response
            ->getBody()
            ->write( json_encode($data, JSON_UNESCAPED_SLASHES | JSON_PRETTY_PRINT) );
    }
]));

// Set up
require_once __DIR__.'/dependencies.php';

$handlers = new handlers($app);
$handlers->installHandlers();

// calendar and events routes
require_once __DIR__.'/routes/calendar/calendar-calendarV2.php';
require_once __DIR__.'/routes/calendar/calendar-eventsV2.php';

// file manager documents routes
require_once __DIR__.'/routes/documents/documents-document.php';
require_once __DIR__.'/routes/documents/documents-ckeditor.php';
require_once __DIR__.'/routes/documents/documents-filemanager.php';
require_once __DIR__.'/routes/documents/documents-sharedocument.php';

// finance routes
require_once __DIR__.'/routes/finance/finance-deposits.php';
require_once __DIR__.'/routes/finance/finance-donationfunds.php';
require_once __DIR__.'/routes/finance/finance-payments.php';
require_once __DIR__.'/routes/finance/finance-pledges.php';

// people families and persons routes
require_once __DIR__.'/routes/people/people.php';
require_once __DIR__.'/routes/people/people-attendees.php';
require_once __DIR__.'/routes/people/people-families.php';
require_once __DIR__.'/routes/people/people-groups.php';
require_once __DIR__.'/routes/people/people-persons.php';

// public routes
require_once __DIR__.'/routes/public/public-data.php';
require_once __DIR__.'/routes/public/public-register.php';

// system sidebar routes
require_once __DIR__.'/routes/sidebar/sidebar-mapicons.php';
require_once __DIR__.'/routes/sidebar/sidebar-menulinks.php';
require_once __DIR__.'/routes/sidebar/sidebar-properties.php';
require_once __DIR__.'/routes/sidebar/sidebar-roles.php';
require_once __DIR__.'/routes/sidebar/sidebar-general-roles.php';
require_once __DIR__.'/routes/sidebar/sidebar-volunteeropportunity.php';

// pastoral care
require_once __DIR__.'/routes/pastoralcare/pastoralcare.php';

// system routes
require_once __DIR__.'/routes/system/system.php';
require_once __DIR__.'/routes/system/system-custom-fields.php';
require_once __DIR__.'/routes/system/system-synchronize.php';
require_once __DIR__.'/routes/system/system-database.php';
require_once __DIR__.'/routes/system/system-gdrp.php';
require_once __DIR__.'/routes/system/system-issues.php';
require_once __DIR__.'/routes/system/system-system-upgrade.php';
require_once __DIR__.'/routes/system/system-timerjobs.php';
require_once __DIR__.'/routes/system/system-setting-individual.php';

// users routes
require_once __DIR__.'/routes/user/user-users.php';
require_once __DIR__.'/routes/user/user-role.php';

// the rest
require_once __DIR__.'/routes/cart.php';
require_once __DIR__.'/routes/geocoder.php';
require_once __DIR__.'/routes/kiosks.php';
require_once __DIR__.'/routes/mailchimp.php';

require_once __DIR__.'/routes/search.php';
require_once __DIR__.'/routes/sundayschool.php';

require_once __DIR__.'/routes/plugins/plugins.php';

// fundraiser route
require_once __DIR__.'/routes/fundraiser/fundraiser.php';

// we load the plugins
if (SessionUser::getCurrentPageName() == 'v2/dashboard') {
    // only dashboard plugins are loaded on the maindashboard page
    $plugins = PluginQuery::create()
        ->filterByCategory('Dashboard', Criteria::EQUAL )
        ->findByActiv(true);


} else {
    $plugins = PluginQuery::create()
        ->filterByCategory('Dashboard', Criteria::NOT_EQUAL )
        ->findByActiv(true);
}

foreach ($plugins as $plugin) {
    $path = __DIR__.'/../Plugins/'.$plugin->getName().'/api/plgnapi.php';
    if (file_exists($path)) {
        require_once $path;
    }
}

// Run app
$app->run();

