<?php

require '../Include/Config.php';

if (\EcclesiaCRM\Bootstrapper::getMaintenanceMode()) {
	http_response_code(503);
	header('Retry-After: 10');
	header('Content-Type: text/html; charset=UTF-8');
	echo '<!doctype html><html lang="en"><head><meta charset="UTF-8"><title>Maintenance mode</title></head><body><h1>Maintenance mode</h1><p>The CRM is temporarily unavailable while a restore is in progress.</p></body></html>';
	exit();
}

// This file is generated by Composer
require_once dirname(__FILE__) . '/../vendor/autoload.php';

use Slim\Factory\AppFactory;
use DI\Container;
use EcclesiaCRM\Slim\dependencies;

use EcclesiaCRM\Slim\Error\handlers;

$rootPath = str_replace('/session/index.php', '', $_SERVER['SCRIPT_NAME']);

// Instantiate the app
$container = new Container();

AppFactory::setContainer($container);

$app = AppFactory::create();

// Register the http cache middleware.
//$app->add( new Cache('private', 0) );

$app->setBasePath($rootPath . "/session");

// Set up
dependencies::install($container, true);

// errors handlers
$handlers = new handlers($app);
$handlers->installHandlers();

// routes
require_once __DIR__ . '/routes/session.php';

// Run app
$app->run();