<?php

namespace EcclesiaCRM;

use EcclesiaCRM\Base\PluginQuery as BasePluginQuery;

use EcclesiaCRM\PluginMenuBarQuery;
use Propel\Runtime\ActiveQuery\Criteria;
use Propel\Runtime\Connection\ConnectionInterface;

/**
 * Skeleton subclass for performing query and update operations on the 'plugin' table.
 *
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
class PluginQuery extends BasePluginQuery
{
    public static function getDashboardPluginsForCurrentUser(): array
    {
        $currentUser = SessionUser::getUser();
        $plugins = self::create()
            ->filterByCategory('Dashboard', Criteria::EQUAL)
            ->usePluginUserRoleQuery()
                ->filterByUserId(SessionUser::getId())
                ->filterByDashboardVisible(true)
            ->endUse()
            ->findByActiv(true);

        $visiblePlugins = [];

        foreach ($plugins as $plugin) {
            if (!$currentUser->isSecurityEnableForPlugin($plugin->getName(), $plugin->getSecurities())) {
                continue;
            }

            $visiblePlugins[] = $plugin;
        }

        return $visiblePlugins;
    }

    public static function getActiveNonDashboardPluginByName(?string $pluginName): ?Plugin
    {
        if (empty($pluginName)) {
            return null;
        }

        return self::create()
            ->filterByCategory('Dashboard', Criteria::NOT_EQUAL)
            ->filterByName($pluginName)
            ->findOneByActiv(true);
    }

    protected function preDelete(ConnectionInterface $con): ?int
    {
        $pluginMenuBarItems = PluginMenuBarQuery::create()->findByPluginName($this->getName());

        foreach ($pluginMenuBarItems as $pluginMenuBarItem) {
            $pluginMenuBarItem->delete();
        }

        return parent::preDelete($con); // TODO: Change the autogenerated stub
    }
}
