<?php

namespace EcclesiaCRM;

use EcclesiaCRM\Base\PluginQuery as BasePluginQuery;

use EcclesiaCRM\PluginMenuBarQuery;
use Propel\Runtime\Connection\ConnectionInterface;

/**
 * Skeleton subclass for performing query and update operations on the 'plugin' table.
 *
 *
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 */
class PluginQuery extends BasePluginQuery
{
    protected function preDelete(ConnectionInterface $con)
    {
        $pluginMenuBarItems = PluginMenuBarQuery::create()->findByPluginName($this->getName());

        foreach ($pluginMenuBarItems as $pluginMenuBarItem) {
            $pluginMenuBarItem->delete();
        }

        return parent::preDelete($con); // TODO: Change the autogenerated stub
    }
}
